/**
 * @file sdcard_err_codes.h
 * @author Pradeepa Senanayake (pradeepa.kck@gmail.com)
 * @date 31 Jan 2016
 * @brief File contains error codes for sdcard_interface API.
 *
 * Include this file in any place to refer to these definitions.
 * 
 * Version v1.0.0
 */

#ifndef _SDCARD_ERR_CODES_H
#define _SDCARD_ERR_CODES_H

#define SDCARD_IF_OP_SUCCESS				0
#define SDCARD_IF_ERR_NOT_INITIALIZED		-1
#define SDCARD_IF_ERR_INVALID_PARAM			-2
#define SDCARD_IF_ERR_FILE_NOT_AVAILABLE	-3
#define SDCARD_IF_ERR_AUDIO_BUFFER_NOT_SET	-4
#define SDCARD_IF_ERR_INVALID_BUFFER_SIZE	-5
#define SDCARD_IF_ERR_BUFFER_OFFSET			-6
#define SDCARD_IF_ERR_EVENT_COUNT			-7
#define SDCARD_IF_ERR_EVENT_NOT_FOUND		-8
#define SDCARD_IF_ERR_FILE_ACCESS			-9


#define SDCARD_IF_WARN_BUFFER_SIZE_SMALL		-200
#define SDCARD_IF_WARN_BUFFER_SIZE_LARGE		-201
#define SDCARD_IF_WARN_LESS_NO_Of_EVENTS_AVAIL	-202
#define SDCARD_IF_WARN_CAPACITY_EIGHTY_PERCENT	-203

#define SDCARD_IF_WARN_FF_DISK_ERROR			-301
#define SDCARD_IF_WARN_FF_INTERNAL_ERROR		-302
#define SDCARD_IF_WARN_FF_NOT_READY				-303
#define SDCARD_IF_WARN_FF_NO_FILE				-304
#define SDCARD_IF_WARN_FF_NO_PATH				-305
#define SDCARD_IF_WARN_FF_INVALID_NAME			-306
#define SDCARD_IF_WARN_FF_DENIED				-307
#define SDCARD_IF_WARN_FF_EXIST					-308
#define SDCARD_IF_WARN_FF_INVALID_OBJECT		-309
#define SDCARD_IF_WARN_FF_WRITE_PROTECTED		-310
#define SDCARD_IF_WARN_FF_INVALID_DRIVE			-311
#define SDCARD_IF_WARN_FF_NOT_ENABLED			-312
#define SDCARD_IF_WARN_FF_NO_FILESYSTEM			-313
#define SDCARD_IF_WARN_FF_MKFS_ABORTED			-314
#define SDCARD_IF_WARN_FF_TIMEOUT				-315
#define SDCARD_IF_WARN_FF_LOCKED				-316
#define SDCARD_IF_WARN_FF_NOT_ENOUGH_CORE		-317
#define SDCARD_IF_WARN_FF_TOO_MANY_OPEN_FILES	-318
#define SDCARD_IF_WARN_FF_INVALID_PARAM			-319
#define SDCARD_IF_WARN_FF_UNKNOWN				-399
#endif
